name = "red-hall-be9f"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "user-db"
database_id = "392def01-1a9b-481c-8768-146b49b1bee2"

[[kv_namespaces]]
binding = "USERS_KV"
id = "95a96194bc6f4bc2b3a3f128a5895627"
preview_id = "9cb382f7787b43929ab920072e23dadc"

[build]
command = "true"

[build.upload]
dir = "src"
format = "modules"

